my_site/my_site/urls.py
from django.contrib import admin
from django.urls import path, include
from p_library import views
# Подключаем media
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user_auth.urls', namespace='user_auth')),
    path('accounts/', include('allauth.urls')),
    path('', include('p_library.urls')),
    path('book_list/book_increment/', views.book_increment),
    path('book_list/book_decrement/', views.book_decrement),
    path('publisher/', views.publisher),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_site/p_library/urls.py
from django.contrib import admin
from django.urls import path
from .views import AuthorCreate, AuthorList, author_create_many, AuthorDelete, AuthorUpdate
from .views import ReadingList, ReadingUpdate, ReadingCreate, ReadingDelete
from .views import FriendList, FriendUpdate, FriendDelete, FriendCreate
from .views import BookUpdate, book_list

app_name = 'p_library'

urlpatterns = [
    path('author/create/', AuthorCreate.as_view(), name='author_create'),
    path('author/', AuthorList.as_view(), name='author_list'),
    path('author/create_many/', author_create_many, name='author_create_many'),
    path('author/<int:pk>/delete/', AuthorDelete.as_view(), name='author_delete'),
    path('author/<int:pk>/', AuthorUpdate.as_view(), name='author_edit'),
    path('reading/create/', ReadingCreate.as_view(), name='reading_edit'),
    path('reading/', ReadingList.as_view(), name='reading_list'),
    path('reading/<int:pk>/', ReadingUpdate.as_view(), name='reading_edit'),
    path('reading/<int:pk>/delete/', ReadingDelete.as_view(), name='reading_delete'),
    path('friend/create/', FriendCreate.as_view(), name='friend_create'),
    path('friend/', FriendList.as_view(), name='friend_list'),
    path('friend/<int:pk>/', FriendUpdate.as_view(), name='friend_edit'),
    path('friend/<int:pk>/delete/', FriendDelete.as_view(), name='friend_delete'),
    path('book_list/<int:pk>/', BookUpdate.as_view(), name='book_edit'),
    path('book_list/', book_list.as_view(), name='book_list'),
]

my_site/p_library/models.py
from django.db import models


# Create your models here.
class Author(models.Model):
    # id = models.UUIDField(default=uuid.uuid4, primary_key=True,
    #                       verbose_name=_("Уникальный ключ"))
    full_name = models.CharField(max_length=256, verbose_name=("Имя автора"))
    birth_year = models.SmallIntegerField(verbose_name=("Год рожения"))
    country = models.CharField(max_length=2, verbose_name=("Страна"))

    def __str__(self):
        return self.full_name

class Publisher(models.Model):
    name = models.TextField()

    def __str__(self):
        return self.name

class Friend(models.Model):
    name = models.CharField(max_length=256, verbose_name="Имя друга")
    books = models.ManyToManyField('p_library.Book',
                                   through='Reading', verbose_name='Читает', related_name='books', blank=True)
                                   # through_fields=('friend', 'book'),
                                   # verbose_name='Читает')

    def __str__(self):
        return self.name

class Book(models.Model):
    ISBN = models.CharField(max_length=13)
    title = models.TextField()
    description = models.TextField()
    year_release = models.SmallIntegerField()
    copy_count = models.SmallIntegerField(default=1)
    price = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, null=True, related_name='books')
    publisher = models.ForeignKey(Publisher, on_delete=models.SET_NULL, null=True)
    readers = models.ManyToManyField('p_library.Friend',
                                     through='Reading', verbose_name='Читатели', related_name='readers')
                                     # through_fields=('book', 'friend'),
                                     # verbose_name='Читатели')
    cover = models.ImageField(upload_to='book_covers', blank=True, verbose_name='Обложка книги')

    def __str__(self):
        return self.title

class Reading(models.Model):
    friend = models.ForeignKey(Friend, on_delete=models.CASCADE, verbose_name="Друг")
    book = models.ForeignKey(Book, on_delete=models.CASCADE, verbose_name="Книга")
    # reader = models.ForeignKey(Friend, on_delete=models.CASCADE, related_name="book_reader", )
    # status = models.NullBooleanField(default=None, verbose_name="Прочитано")

    def __str__(self):
        return "-".join((str(self.friend), str(self.book),))
                         # str(self.status),))


# Код из Вебинара

# class Friend(models.Model):
#     name = models.CharField(max_length=256, default='Имя', verbose_name="Имя друга")
#     books = models.ManyToManyField("p_library.Book", verbose_name="Книги",
#                                    through="p_library.BookReading",
#                                    through_fields=('friend', 'r_book', 'completion',))
#
#     def __str__(self):
#         return self.name
#
#
# class BookReading(models.Model):
#     friend = models.ForeignKey("p_library.Friend", on_delete=models.CASCADE,
#                                null=True,
#                                verbose_name="Читатель",
#                                related_name="friend")
#     r_book = models.ForeignKey("p_library.Book", on_delete=models.CASCADE,
#                              null=True,
#                              verbose_name="Книга",
#                              related_name="reading_book")
#     completion = models.NullBooleanField(default=None,
#                                          verbose_name="Прочитано")
#
#     def __str__(self):
#         return "-".join((str(self.r_book),
#                          str(self.friend),
#                          str(self.completion),))

my_site/p_library/forms.py
from django import forms
from .models import Author, Reading, Friend, Book

class AuthorForm(forms.ModelForm):
    # Виджет для изменения типа ввода поля
    # full_name = forms.CharField(widget=forms.TextInput)

    class Meta:
        model = Author
        fields = '__all__'

class ReadingForm(forms.ModelForm):
    class Meta:
        model = Reading
        fields = '__all__'

class FriendForm(forms.ModelForm):
    class Meta:
        model = Friend
        fields = '__all__'

class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = '__all__'

my_site/p_library/views.py
from django.http import HttpResponse

from p_library.models import Book
from .forms import BookForm

from p_library.models import Publisher
from django.template import loader
from django.shortcuts import redirect, render

from .models import Author
from .forms import AuthorForm

from .models import Reading
from .forms import ReadingForm

from .models import Friend
from .forms import FriendForm

from django.views.generic import CreateView, ListView, DeleteView, UpdateView, DetailView
from django.urls import reverse_lazy

from django.http.response import HttpResponseRedirect

from django.forms import formset_factory
# AuthorFormSet = formset_factory(AuthorForm)

class AuthorCreate(CreateView):
    model = Author
    form_class = AuthorForm
    success_url = reverse_lazy('p_library:author_list')
    template_name = 'author_edit.html'

    def post(self, request, *args, **kwargs):
        context = {}
        user = request.user
        if not user.is_authenticated:
            return redirect('user_auth:index')
        if not user.is_superuser:
            context['message'] = "Вы не супер пользователь!"
            return render(request, 'access.html', context)
        return super().post(request, *args, **kwargs)

class ReadingCreate(CreateView):
    model = Reading
    form_class = ReadingForm
    success_url = reverse_lazy('p_library:reading_list')
    template_name = 'reading_edit.html'

    def post(self, request, *args, **kwargs):
        context = {}
        user = request.user
        if not user.is_authenticated:
            return redirect('user_auth:index')
        if not user.is_superuser:
            context['message'] = "Вы не супер пользователь!"
            return render(request, 'access.html', context)
        return super().post(request, *args, **kwargs)

class FriendCreate(CreateView):
    model = Friend
    form_class = FriendForm
    success_url = reverse_lazy('p_library:friend_list')
    template_name = 'reading_edit.html'

    def post(self, request, *args, **kwargs):
        context = {}
        user = request.user
        if not user.is_authenticated:
            return redirect('user_auth:index')
        if not user.is_superuser:
            context['message'] = "Вы не супер пользователь!"
            return render(request, 'access.html', context)
        return super().post(request, *args, **kwargs)

class AuthorList(ListView):
    model = Author
    template_name = 'author_list.html'

class ReadingList(ListView):
    model = Reading
    template_name = 'reading_list.html'

class FriendList(ListView):
    model = Friend
    template_name = 'friend_list.html'

class AuthorUpdate(UpdateView):
    model = Author
    fields = ["full_name", "birth_year", "country"]
    success_url = reverse_lazy('p_library:author_list')
    template_name = 'author_edit.html'

    def post(self, request, *args, **kwargs):
        context = {}
        user = request.user
        if not user.is_authenticated:
            return redirect('user_auth:index')
        if not user.is_superuser:
            context['message'] = "Вы не супер пользователь!"
            return render(request, 'access.html', context)
        return super().post(request, *args, **kwargs)

class BookUpdate(UpdateView):
    model = Book
    fields = ['ISBN', 'title', 'description', 'year_release', 'copy_count', 'price', 'author', 'publisher', 'cover',]
    success_url = reverse_lazy('p_library:index')
    template_name = 'book_edit.html'

    def post(self, request, *args, **kwargs):
        context = {}
        user = request.user
        if not user.is_authenticated:
            return redirect('user_auth:index')
        if not user.is_superuser:
            context['message'] = "Вы не супер пользователь!"
            return render(request, 'access.html', context)
        return super().post(request, *args, **kwargs)

class ReadingUpdate(UpdateView):
    model = Reading
    fields = ['friend', 'book']
    success_url = reverse_lazy('p_library:reading_list')
    template_name = 'reading_edit.html'

    def post(self, request, *args, **kwargs):
        context = {}
        user = request.user
        if not user.is_authenticated:
            return redirect('user_auth:index')
        if not user.is_superuser:
            context['message'] = "Вы не супер пользователь!"
            return render(request, 'access.html', context)
        return super().post(request, *args, **kwargs)

class FriendUpdate(UpdateView):
    model = Friend
    fields = ['name', 'books']
    success_url = reverse_lazy('p_library:friend_list')
    template_name = 'reading_edit.html'

    def post(self, request, *args, **kwargs):
        context = {}
        user = request.user
        if not user.is_authenticated:
            return redirect('user_auth:index')
        if not user.is_superuser:
            context['message'] = "Вы не супер пользователь!"
            return render(request, 'access.html', context)
        return super().post(request, *args, **kwargs)

class AuthorDelete(DeleteView):
    model = Author
    form_class = AuthorForm
    fields = ["full_name", "birth_year", "country"]
    success_url = reverse_lazy('p_library:author_list')
    template_name = 'author_delete.html'

    def post(self, request, *args, **kwargs):
        context = {}
        user = request.user
        if not user.is_authenticated:
            return redirect('user_auth:index')
        if not user.is_superuser:
            context['message'] = "Вы не супер пользователь!"
            return render(request, 'access.html', context)
        self.delete(request)
        return redirect('p_library:author_list')

class ReadingDelete(DeleteView):
    model = Reading
    form_class = ReadingForm
    # fields = ['friend', 'book']
    success_url = reverse_lazy('p_library:reading_list')
    template_name = 'reading_delete.html'

    def post(self, request, *args, **kwargs):
        context = {}
        user = request.user
        if not user.is_authenticated:
            return redirect('user_auth:index')
        if not user.is_superuser:
            context['message'] = "Вы не супер пользователь!"
            return render(request, 'access.html', context)
        return super().post(request, *args, **kwargs)

class FriendDelete(DeleteView):
    model = Friend
    fields = ['name', 'books']
    success_url = reverse_lazy('p_library:friend_list')
    template_name = 'reading_delete.html'

    def post(self, request, *args, **kwargs):
        context = {}
        user = request.user
        if not user.is_authenticated:
            return redirect('user_auth:index')
        if not user.is_superuser:
            context['message'] = "Вы не супер пользователь!"
            return render(request, 'access.html', context)
        self.delete(request)
        return redirect('p_library:friend_list')

def books_list(request):
    return redirect('/book_list/')

class book_list(ListView):
    model = Book
    form_class = BookForm
    context_object_name = 'books'
    template_name = 'book_list.html'

def publisher(request):
    template = loader.get_template('publisher.html')
    publishers = Publisher.objects.all()
    publishers_data = {
        "publishers": publishers,
    }
    return HttpResponse(template.render(publishers_data, request))

def book_increment(request):
    context = {}
    user = request.user
    if not user.is_authenticated:
        return redirect('user_auth:index')
    if not user.is_superuser:
        context['message'] = "Вы не супер пользователь!"
        return render(request, 'access.html', context)
    if request.method == 'POST':
        book_id = request.POST['id']
        if not book_id:
            return redirect('/book_list/')
        else:
            book = Book.objects.filter(id=book_id).first()
            if not book:
                return redirect('/book_list/')
            book.copy_count += 1
            book.save()
        return redirect('/book_list/')
    else:
        redirect('/book_list/')

def book_decrement(request):
    context = {}
    user = request.user
    if not user.is_authenticated:
        return redirect('user_auth:index')
    if not user.is_superuser:
        context['message'] = "Вы не супер пользователь!"
        return render(request, 'access.html', context)
    if request.method == 'POST':
        book_id = request.POST['id']
        if not book_id:
            redirect('/book_list/')
        else:
            book = Book.objects.filter(id=book_id).first()
            if not book:
                redirect('/book_list/')
            if book.copy_count < 1:
                book.copy_count = 0
            else:
                book.copy_count -= 1
            book.save()
        return redirect('/book_list/')
    else:
        return redirect('/book_list/')


def is_save(author_form):
    try:
        author_form.save()
        return True
    except BaseException:
        return False

def author_create_many(request):
    AuthorFormSet = formset_factory(AuthorForm, extra=3)
    if request.method == 'POST':
        author_formset = AuthorFormSet(request.POST, request.FILES, prefix='author')
        if author_formset.is_valid():
            for author_form in author_formset:
                if is_save(author_form):
                    pass
                else:
                    return HttpResponseRedirect(reverse_lazy('p_library:author_list'))
            return HttpResponseRedirect(reverse_lazy('p_library:author_list'))
    else:
        author_formset = AuthorFormSet(prefix='author')
    return render(request, 'manage_authors.html', {'author_formset': author_formset})

my_site/templates/p_library/author_delete.html
{% extends 'base.html' %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <input type="submit" value="Удалить">
    </form>
{% endblock %}

my_site/templates/p_library/author_edit.html
{% extends 'base.html' %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Сохранить">
    </form>
    {% if author.id %}
        <a href="/author/{{ author.id }}/delete">Удалить автора</a>
    {% else %}
        <a href="/author/{{ author.id }}/delete" hidden>Удалить автора</a>
    {% endif %}
{% endblock %}

my_site/templates/p_library/author_list.html
{% extends 'base.html' %}

{% block content %}
    <a href="/">Домой</a>
    <ul>
        {% for author in object_list %}
            <li><a href="{{author.id}}/">{{ author.id }}: {{ author.full_name }}</a></li>
        {% endfor %}
    </ul>
    <a href="/author/create/">Создать нового автора</a>
    <a href="/author/create_many/">Создать несколько авторов</a>
{% endblock %}

my_site/templates/p_library/book_edit.html
{% extends 'base.html' %}

{% block content %}
    <!--enctype="multipart/form-data" для сохранения картинок-->
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Сохранить">
    </form>
    {% if author.id %}
        <a href="/author/{{ book.id }}/delete">Удалить книгу</a>
    {% else %}
        <a href="/author/{{ book.id }}/delete" hidden>Удалить книгу</a>
    {% endif %}
{% endblock %}

my_site/templates/p_library/book_list.html
{% extends 'base.html' %}

{% block content %}
    <h1>Привет, {{ username }}! Добро пожаловать в мою библиотеку.</h1>
    <p>Добро пожаловать в мою библиотеку.</p>
    <p>Тут собрано {{ books|length }} книг из моей личной коллекции.</p>
    <table border="1">
        {% for book in books %}
        <tr>
            <td style="padding-right:5; padding-left:5">{{ forloop.counter }}</td>
            <td><a href="{{ book.id }}/">{{ book.title }}</a></td>
            <td>
                {% if book.cover %}
                    <img height="100" width="100" src="{{ book.cover.url }}" alt="Book_cover">
                {% else %}
                    <p>Обложка</p>
                {% endif %}
            </td>
            <td>{{ book.ISBN }}</td>
            <td>{{ book.description }}</td>
            <td>{{ book.year_release }}</td>
            <td>{{ book.author.full_name }}</td>
            <td>{{ book.author.country }}</td>
            <td style="padding-right:5; padding-left:5">{{ book.copy_count }}</td>
            <td>
                <ul style="padding-right:20; padding-left:0; list-style-type: none">
                    <p style="position: relative, margine:0">Читают:</p>
                    {% for friend in book.readers.all %}
                        <li>
                            <p>{{ friend.name }}</p>
                        </li>
                    {% endfor %}
                </ul>
            </td>
            <td>
                <form action="/book_list/book_increment/" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <input type="hidden" name="id" value="{{ book.id }}"/>
                <input type="submit" value="Увеличить количество"/>
            </form>
            <form action="/book_list/book_decrement/" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <input type="hidden" name="id" value="{{ book.id }}"/>
                <input type="submit" value="Уменьшить количество"/>
            </form>
            </td>
        </tr>
        {% endfor %}
    </table>
{% endblock %}

my_site/templates/p_library/friend_list.html
{% extends 'base.html' %}

{% block content %}
    <a href="/">Домой</a>
    <h2>Друзья:</h2>
    <ul>
        {% for friend in object_list %}
            <li>
                <a href="{{friend.id}}/">{{ friend.id }}: Друг {{ friend.name }} читает:</a>
                <ul>
                    {% for book in friend.books.all %}
                        <li>
                            <p>Книга: {{ book.title }}</p>
                        </li>
                    {% endfor %}
                </ul>
            </li>
        {% endfor %}
    </ul>
    <a href="/friend/create/">Добавить</a>
{% endblock %}

my_site/templates/p_library/manage_authors.html
{% extends 'base.html' %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{author_formset.management_form}}
        {% for form in author_formset %}
            {{ form.as_p }}
            <br>
        {% endfor %}
        <input type="submit" value="Сохранить">
    </form>
{% endblock %}

my_site/templates/p_library/publisher.html
{% extends 'base.html' %}
{% block content %}
    <a href="/">Домой</a>
    <h1>Издательства:</h1>
    {% for publisher in publishers %}
        <ul class="list-group" >
            <li class="list-group-item">
                <h3>Издательство: {{ publisher.name }}, издано: <span class="badge badge-success badge-pill"> {{publisher.book_set.all|length}}</span></h3>
                <ul class="list-group">
                    {% for book in publisher.book_set.all %}
                        <li class="list-group-item">
                            <p>Автор: {{ book.author }}</p>
                            <p>Книга: {{ book.title }}</p>
                        </li>
                    {% endfor %}
                </ul>
            </li>
        </ul>
    {% endfor %}
{% endblock %}

my_site/templates/p_library/reading_delete.html
{% extends 'base.html' %}

{% block content %}
    {% if reading.id %}
        <h2>Удалить сессию?</h2>
        <form method="post">
            {% csrf_token %}
            <input type="submit" value="Удалить">
        </form>
    {% else %}
        <h2>Удалить {{ friend.name }}?</h2>
        <form method="post">
            {% csrf_token %}
            <input type="submit" value="Удалить">
        </form>
    {% endif %}
{% endblock %}

my_site/templates/p_library/reading_edit.html
{% extends 'base.html' %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Сохранить">
    </form>
    {% if reading.id %}
        <a href="/reading/{{ reading.id }}/delete">Удалить</a>
    {% else %}
        {% if friend.id %}
            <a href="/friend/{{ friend.id }}/delete">Удалить</a>
        {% endif %}
        <a href="/reading/{{ reading.id }}/delete" hidden>Удалить</a>
    {% endif %}
{% endblock %}

my_site/templates/p_library/reading_list.html
{% extends 'base.html' %}

{% block content %}
    <a href="/">Домой</a>
    <h2>В настоящее время читают:</h2>
    <ul>
        {% for reading in object_list %}
            <li>
                <a href="{{reading.id}}/">{{ reading.id }}: Друг {{ reading.friend.name }} читает: {{ reading.book }}</a>
            </li>
        {% endfor %}
    </ul>
    <a href="/reading/create/">Создать</a>
{% endblock %}